sonar.projectKey=${env.SONAR_PROJECT_KEY}
sonar.projectName=Intelligent S3 File Renaming
sonar.projectVersion=0.1.0

sonar.sources=backend/src/main/java,frontend/src/app
sonar.tests=backend/src/test/java,frontend/src
sonar.test.inclusions=backend/src/test/java/**/*.java,frontend/src/**/*.spec.ts

sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/s3-renaming-frontend/lcov.info

sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/coverage/**,**/.angular/**,**/.aws-sam/**
sonar.sourceEncoding=UTF-8

